import React from "react";
import DestinationsCard from "./DestinationsCard";


const destinations = [
  {
    id: "1",
    name: "Mulakbugak Spring Falls",
    image: "https://source.unsplash.com/1000x700/?Mulakbugak%20Spring%20Falls",
    description: "Mulakbugak is a spring type waterfall famed for its clean, cold, and crystal clear water. As stated by the locals “Kun ika iinitan , digdi ka magdalagan, paglabtu mo ika tulos tatakigan”, you can visit here and experience the cold refreshing water.",
    location: "Tinapian, Manito, Albay",
    category: "Falls",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "2",
    name: "Nag Aso Boiling Lake",
    image: "https://source.unsplash.com/1000x700/?Nag%20Aso%20Boiling%20Lake",
    description: "Nag-Aso Boiling Lake is considered as prime tourist destination in the municipality of Manito. It measures one hectare bordered by a lush tapestry of green fields and abundant trees which makes it as the largest boiling lake in Bicol that also provides habitat for flora and fauna.",
    location: "Hulogan, Manito, Albay",
    category: "Lakes and Pond",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "3",
    name: "Aqua Silvi Mangrove Site",
    image: "https://source.unsplash.com/1000x700/?Aqua%20Silvi%20Mangrove%20Site",
    description: "From Bgy. Marigondon, boats ferry visitors to the mangrove area visitor center where they may see the mangrove forest up close, Immerse in the calm and quiet of the surroundings, and enjoy the picturesque vistas.",
    location: "Marigondon, Pio Duran, Albay",
    category: "Marine Park (e.g. aquarium, open parks)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "4",
    name: "Bulalacao Cave Exploration",
    image: "https://source.unsplash.com/1000x700/?Bulalacao%20Cave%20Exploration",
    description: "The 30-minute hike to Bulalacao Cave is the perfect trial adventure. It begins with a gradual descent through grassy, undulating hills puntuated here and there by the lone bahay kubo and errant farm animals.",
    location: "Flores, Pio Duran, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "5",
    name: "Muladbucad White Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Muladbucad%20White%20Beach%20Resort",
    description: "A resort that can be considered as one of the few white beaches situated in Albay and is accessible by land. An hour away from the City of Legazpi, is a place where you can feel the soothing ambiance of nature, vibe in with the melody of chirping birds while relaxing with the whisper of the waves.",
    location: "Hulogan, Manito, Albay",
    category: "Unique Natural Landscape / Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "6",
    name: "Kalabidungan Cave Exploration",
    image: "https://source.unsplash.com/1000x700/?Kalabidungan%20Cave%20Exploration",
    description: "Kalabidungan Cave is a shallow cave with a short underground river whose depth has yet to be officially measured. Within it's dark cavern are stunning flowstones, bacon draperies, stalactites, stalagmites, and a healthy colony of bats hence the cave's name, Kalabidungan Cave",
    location: "Rawis, Pio Duran, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "7",
    name: "Oras Falls",
    image: "https://source.unsplash.com/1000x700/?Oras%20Falls",
    description: "It is a single thin cascade over which thick foliage forms a natural backdrop.",
    location: "Oras, Tabaco City, Albay",
    category: "Falls",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "8",
    name: "Abion Falls",
    image: "https://source.unsplash.com/1000x700/?Abion%20Falls",
    description: "Located in Sitio Bagong Sirang Brgy. Tinapian Manito Albay, is where you can find the breath-taking view of this waterfalls that will ease your fatigue and be amazed with its pristine cool water and the refreshing feels of the waterfalls.",
    location: "Tinapian, Manito, Albay",
    category: "Falls",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "9",
    name: "Zoeis Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Zoeis%20Beach%20Resort",
    description: "Located in Brgy Cawayan Manito, Albay is where you can find Zoei’s Beach Resort. It is a private resort that can be considered as one of the few beaches situated in Albay and is also accessible by land and is an hour away from the City of Legazpi.",
    location: "Cawayan, Manito, Albay",
    category: "Unique Natural Landscape / Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "10",
    name: "Busay Falls - Malilipot",
    image: "https://source.unsplash.com/1000x700/?Busay%20Falls%20-%20Malilipot",
    description: "Busay Falls is a popular day trip destination for local tourists. The seven-tiered falls is considered one of the highest waterfalls in the country descending in stages from a height of 250 meters cascading into seven small pools.",
    location: "Barangay 1, Malilipot, Albay",
    category: "Falls",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "11",
    name: "Mayon Planetarium and Science Park",
    image: "https://source.unsplash.com/1000x700/?Mayon%20Planetarium%20and%20Science%20Park",
    description: "Built on a protected area nestled on the slopes of beautiful Mt. Mayon. It serves as a learning center and a tourist spot that boasts a birds-eye view of the whole city.",
    location: "Magapo, Tabaco City, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "12",
    name: "Manito Mangrove Area",
    image: "https://source.unsplash.com/1000x700/?Manito%20Mangrove%20Area",
    description: "Manito Eco Park will surely give you an amazing experience, having that feeling of tranquility while enjoying the scenic beauty of Manito’s very own Mangrove Eco Park indulging in its rich biodiversity.",
    location: "It-Ba, Manito, Albay",
    category: "Unique Natural Landscape / Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "13",
    name: "San Miguel Fish Sanctuary and Marine Reserve",
    image: "https://source.unsplash.com/1000x700/?San%20Miguel%20Fish%20Sanctuary%20and%20Marine%20Reserve",
    description: "San Miguel Fish Sanctuary and Marine Reserve is a 2.25 square kilometer protected area located at Barangay Sagurong. It was adjudged as 2nd best-managed coral reef in the entire Philippines.",
    location: "Sagurong, Tabaco City, Albay",
    category: "Dive Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "14",
    name: "Natunawan Cove",
    image: "https://source.unsplash.com/1000x700/?Natunawan%20Cove",
    description: "A natural cove that formed during a catastrophe that hit Tabaco. According to the narratives of former inhabitants of the place, it was completely submerged by storm surge during Typhoon Trix in 1952 thus it was called \"Natunawan\".",
    location: "San Carlos, Tabaco City, Albay",
    category: "Unique Natural Landscape / Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "15",
    name: "Cabulwangan Hill Spring Resort",
    image: "https://source.unsplash.com/1000x700/?Cabulwangan%20Hill%20Spring%20Resort",
    description: "A cold spring resort found beside the lush mountain of Malilipot, Albay. It is a haven for nature lovers.",
    location: "Barangay 1, Malilipot, Albay",
    category: "Lakes and Pond",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "16",
    name: "Sumlang Lake",
    image: "https://source.unsplash.com/1000x700/?Sumlang%20Lake",
    description: "Sumlang Lake, with an area of 9.21 hectares is located in Barangay Sumlang, Camalig, Albay approximately three (3) kilometers from the Poblacion (Camalig Town Center) and 11 kms. from Legazpi City, the nearest growth center.",
    location: "Sumlang, Camalig, Albay",
    category: "Lakes and Pond",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "17",
    name: "Diamond Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Diamond%20Beach%20Resort",
    description: "Diamond Beach Parong Resort is a place used for vacation, relaxation or as a daytime getaway. This stunning resort in town of Manito combines the scenic qualities and escapist nature of hot spring facing the Mount Mayon Volcano.",
    location: "Pawa, Manito, Albay",
    category: "Unique Natural Landscape / Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "18",
    name: "Namuropuwerta Rock Formation and Mataas Beach",
    image: "https://source.unsplash.com/1000x700/?Namuropuwerta%20Rock%20Formation%20and%20Mataas%20Beach",
    description: "Located in Barangay Mataas , the majestic rock formations seem handcrafted by nature, perfect for an action-packed climbing adventure. The uniquely embedded rock formation was formed overtime through the continous spashing of the waves during high tide.",
    location: "Mataas, Bacacay, Albay",
    category: "Coastal Landscape and Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "19",
    name: "Adam Rock Formation, Marine Reserve and Fish Sanctuary",
    image: "https://source.unsplash.com/1000x700/?Adam%20Rock%20Formation,%20Marine%20Reserve%20and%20Fish%20Sanctuary",
    description: "The Adam rock formation found in Uson is unremarkable, but is sure to amaze visitors and visitors alike with its gorgeous appearance, forged by nature's invisible hand. Uson, Buang, Pongco-Bonga fish sanctuary is one of the largest marine protected areas in Bicol region.",
    location: "Uson, Bacacay, Albay",
    category: "Unique Natural Landscape / Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "20",
    name: "Cagbulawan Beach",
    image: "https://source.unsplash.com/1000x700/?Cagbulawan%20Beach",
    description: "Its name is derived from the word \"Bulawan\" with means gold because of its golden colored sand.",
    location: "Namanday, Bacacay, Albay",
    category: "Unique Natural Landscape / Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "21",
    name: "Cagbungahan Beach",
    image: "https://source.unsplash.com/1000x700/?Cagbungahan%20Beach",
    description: "White sand beach and there are available cottages for rent and visitors can request a delicious freshly cooked lunch on the site.",
    location: "Namanday, Bacacay, Albay",
    category: "Unique Natural Landscape / Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "22",
    name: "El Miro De Shie Integrated Farm",
    image: "https://source.unsplash.com/1000x700/?El%20Miro%20De%20Shie%20Integrated%20Farm",
    description: "An accredited Farm Tourism Site, Agricultural Training Institute and TESDA located in Barangay Salugan approximately two (2) kilometers from the Poblacion (Camalig) and 12 kms. from Legazpi City, the nearest growth center .",
    location: "Salugan, Camalig, Albay",
    category: "Other Natural Attractions (e.g. century old trees/forest, endemic species)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "23",
    name: "Black Sand Beaches",
    image: "https://source.unsplash.com/1000x700/?Black%20Sand%20Beaches",
    description: "A summer getaway for water-loving travelers. During summer and Holy Week, its long black sand beaches are occupied by families, balik-bayan and other foreign tourists.",
    location: "Hindi, Bacacay, Albay",
    category: "Unique Natural Landscape / Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "24",
    name: "Quituinan Ranch",
    image: "https://source.unsplash.com/1000x700/?Quituinan%20Ranch",
    description: "Located in Quituinan Hills, a former Japanese camp and important landmark, showcased the clear vista of the Mayon Volcano, Albay Gulf and other parts of Albay. Situated approximately three (3) kilometers from the Poblacion (Camalig) and 17 kms. from Legazpi City, the nearest growth center .",
    location: "Brgy. Tinago, Camalig, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "25",
    name: "Solong Eco-Park",
    image: "https://source.unsplash.com/1000x700/?Solong%20Eco-Park",
    description: "A newly developed DOT accredited Farm Site situated approximately 14 kms from the Poblacion (Camalig Town Center and 9 kms from the BIA, the nearest gateway.",
    location: "Brgy. Solong, Camalig, Albay",
    category: "Other Natural Attractions (e.g. century old trees/forest, endemic species)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "26",
    name: "Little Coron / Cagbulacao Rock Formation",
    image: "https://source.unsplash.com/1000x700/?Little%20Coron%20/%20Cagbulacao%20Rock%20Formation",
    description: "Lime stone rock formation is located in Barangay Cagbulacao. It was also featured in one travel shows\" Byahe ni Drew\".",
    location: "Cagbulacao, Bacacay, Albay",
    category: "Coastal Landscape and Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "27",
    name: "Quitinday Green Hills",
    image: "https://source.unsplash.com/1000x700/?Quitinday%20Green%20Hills",
    description: "Different coned shape hills formations nearly similar of Bohol’s Chocolate Hills with two caves that can be found on top of a hill. It is located 15 kms. from the Poblacion(Camalig Town Center) and 19 kms from the BIA, the nearest gateway.",
    location: "Barangay Quitinday, Camalig, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "28",
    name: "Nagsagimsim Island (Monkey Sanctuary)",
    image: "https://source.unsplash.com/1000x700/?Nagsagimsim%20Island%20(Monkey%20Sanctuary)",
    description: "This Island of Barangay Manaet is the home for monkeys, the only inhabitants of the said island. That is why, most tourist visited the pace as called monkey Island\"",
    location: "Manaet, Bacacay, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "29",
    name: "Sula Channel",
    image: "https://source.unsplash.com/1000x700/?Sula%20Channel",
    description: "Sula Channel is a marine channel linking Albay Gulf to the Pacific Ocean. It is located near Bgy. Sula, Cagraray Island, thus its name. During Spanish times, the coves in the area were used to shelter galleons. Currently, these are still used as haven for ships during bad weather.",
    location: "Sula, Bariw, Namantao, Bacacay, Albay",
    category: "Unique Natural Landscape / Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "30",
    name: "Pinamuntugan Island",
    image: "https://source.unsplash.com/1000x700/?Pinamuntugan%20Island",
    description: "Pinamuntugan Island is now an emerging tourist site located in Barangay Langaton, Bacacay, Albay. This is popularly known because of its color white sand and pristine beauty. There are also available cottage for rent and can also bring a tent for some overnight getaway.",
    location: "Langaton, Bacacay, Albay",
    category: "Unique Natural Landscape / Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "31",
    name: "Mount Manaet",
    image: "https://source.unsplash.com/1000x700/?Mount%20Manaet",
    description: "This exceptional view is a wonder display of nature's gift. Mt. Manaet trekking is one of the Emerging tourism activities here in Bacacay. Group of mountaineers are the frequent visitors of the site and they are all speechless when they reach the top because of the picture perfect view of Mayon.",
    location: "Manaet, Bacacay, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "32",
    name: "Tanagan Falls",
    image: "https://source.unsplash.com/1000x700/?Tanagan%20Falls",
    description: "Experience serenity and listen to the music of nature. You can also enjoy a relaxing massage as you let the water plunge on your body.",
    location: "Tanagan, Bacacay, Albay",
    category: "Falls",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "33",
    name: "Pighulugan Cave",
    image: "https://source.unsplash.com/1000x700/?Pighulugan%20Cave",
    description: "Bacacay boast of various caves with mostly limestone rock formation & well-developed stalactites and stalagmites. This cave is ideal for tourist who want spelunking adventures. These can be accessed by hiking & climbing through dense forest.",
    location: "Misibis, Bacacay, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "34",
    name: "Mataas Cave",
    image: "https://source.unsplash.com/1000x700/?Mataas%20Cave",
    description: "Bacacay boast of various caves with mostly limestone rock formation & well-developed stalactites and stalagmites. This cave is ideal for tourist who want spelunking adventures. These can be accessed by hiking & climbing through dense forest.",
    location: "Mataas, Bacacay, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "35",
    name: "Cagbulacao Cave",
    image: "https://source.unsplash.com/1000x700/?Cagbulacao%20Cave",
    description: "Bacacay boast of various caves with mostly limestone rock formation & well-developed stalactites and stalagmites. This cave is ideal for tourist who want spelunking adventures. These can be accessed by hiking & climbing through dense forest.",
    location: "Cagbulacao, Bacacay, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "36",
    name: "Nagtikwil Cave",
    image: "https://source.unsplash.com/1000x700/?Nagtikwil%20Cave",
    description: "Bacacay boast of various caves with mostly limestone rock formation & well-developed stalactites and stalagmites. This cave is ideal for tourist who want spelunking adventures. These can be accessed by hiking & climbing through dense forest.",
    location: "Cagbulacao, Bacacay, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "37",
    name: "Boton Cave",
    image: "https://source.unsplash.com/1000x700/?Boton%20Cave",
    description: "Bacacay boast of various caves with mostly limestone rock formation & well-developed stalactites and stalagmites. This cave is ideal for tourist who want spelunking adventures. These can be accessed by hiking & climbing through dense forest.",
    location: "Cagbulacao, Bacacay, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "38",
    name: "Tanagan Cave",
    image: "https://source.unsplash.com/1000x700/?Tanagan%20Cave",
    description: "Bacacay boast of various caves with mostly limestone rock formation & well-developed stalactites and stalagmites. This cave is ideal for tourist who want spelunking adventures. These can be accessed by hiking & climbing through dense forest.",
    location: "Tanagan, Bacacay, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "39",
    name: "Jovellar Underground River, Caves and Rainforest",
    image: "https://source.unsplash.com/1000x700/?Jovellar%20Underground%20River,%20Caves%20and%20Rainforest",
    description: "An underground river cave passing underneath the rice and coconut plantation with formation of stalactites and stalagmites.  It can be explored aboard a kayak or raft.  Located in Brgy. Quitinday, 1 km from the poblacion town.",
    location: "Quitinday, Jovellar, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "40",
    name: "SIGPIT WATERFALLS",
    image: "https://source.unsplash.com/1000x700/?SIGPIT%20WATERFALLS",
    description: "The very famous waterfalls in the locality, known as \"Sigpit\" because of its narrow and long body of water that lays between large formation of rocks. Attracts domestic and foreign tourists because of its green and cold refreshing water. Located in Brgy. Quitinday, 0.8 km from the poblacion town.",
    location: "Quitinday, Jovellar, Albay",
    category: "Falls",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "41",
    name: "NAGLAUS UNDERGROUND RIVER CAVE",
    image: "https://source.unsplash.com/1000x700/?NAGLAUS%20UNDERGROUND%20RIVER%20CAVE",
    description: "Located in Brgy. Del Rosario, 7 kms. from the poblacion town, traversable underground river that directly leads to Nabasan, Daraga, Albay. Naturally inspired by nature, at the mouth of the cave, a clear & cold small lagoon is framed by rocks.",
    location: "Del Rosario, Jovellar, Albay",
    category: "River and Landscape (includes subterranean rivers)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "42",
    name: "Amater Spring Resort",
    image: "https://source.unsplash.com/1000x700/?Amater%20Spring%20Resort",
    description: "Amater Spring Resort is a nature attraction with pool of fresh and very cold water from natural spring which makes it ideal and popular during hot summer days.",
    location: "Tanawan, Malinao, Albay",
    category: "Lakes and Pond",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "43",
    name: "MAGTAGUINTING FALLS",
    image: "https://source.unsplash.com/1000x700/?MAGTAGUINTING%20FALLS",
    description: "Cascading clear, crystal water to more than 70 ft in height, located at Brgy. Bagacay, 3 kms from the poblacion town.",
    location: "Bagacay, Jovellar, Albay",
    category: "Falls",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "44",
    name: "QUIBARAW FALLS",
    image: "https://source.unsplash.com/1000x700/?QUIBARAW%20FALLS",
    description: "Surrounded by a lagoon framed by rocks located at Brgy. SAn Vicente, 3 kms away from the poblacion town. It features a limestone karst mountain landscape with a full mountain landscape that protects a forest.",
    location: "San Vicente, Jovellar, Albay",
    category: "Falls",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "45",
    name: "Vera Falls",
    image: "https://source.unsplash.com/1000x700/?Vera%20Falls",
    description: "Vera Falls is a stunning waterfall of very clear and cold water coming out of rocks of the mountain. A few minutes of trekking is needed to get down to the area.",
    location: "Soa / Bulang, Malinao, Albay",
    category: "Falls",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "46",
    name: "MAYANPAYAN HILLS & NATURAL PARK",
    image: "https://source.unsplash.com/1000x700/?MAYANPAYAN%20HILLS%20&%20NATURAL%20PARK",
    description: "Panoramic mountain views with the majestic mayon volcano on its background, the sunrise/sunset over the top of the mountain will await the backpackers to conquer the place. Located at Brgy. San Roque, 3 kms. away from the poblacion town going to the newly built Jovellar-Donsol highway.",
    location: "San Roque, Jovellar, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "47",
    name: "MEKAWA LAGOON",
    image: "https://source.unsplash.com/1000x700/?MEKAWA%20LAGOON",
    description: "Located in Brgy. Quitinday, roughly 700 mtrs from the Jovellar Underground River flowing down to Sigpit Falls. It is flowing and cold that refreshes anyone who explore the place.",
    location: "Quitinday, Jovellar, Albay",
    category: "Lakes and Pond",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "48",
    name: "Tigbao Highlands",
    image: "https://source.unsplash.com/1000x700/?Tigbao%20Highlands",
    description: "The adrenaline for a nature adventure makes Tigbao Highlands a local version of Scotland. It is now becoming a favorite location for a quick getaway because of its lush meadows and hay-like trees for travelers who love to unwind and meditate.",
    location: "Oma-Oma, Ligao City, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "49",
    name: "SILAY CAVE 1",
    image: "https://source.unsplash.com/1000x700/?SILAY%20CAVE%201",
    description: "Located at Brgy. Quitinday merely 500 to 600 meters from the holding area and about 100 to 200 meters from the underground river. To reach the cave, you’ll cross the river taking a bamboo bridge and climb uphill. Provide a variety of rock formations from the entrance and many more as you go deeper.",
    location: "Quitinday, Jovellar, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "50",
    name: "Mount Quiasog Monolith Rock",
    image: "https://source.unsplash.com/1000x700/?Mount%20Quiasog%20Monolith%20Rock",
    description: "Located at Macabugos-Tambo border, Mount Quiasog is a karstic environment with systems of caves, rolling hills, and a towering limestone monolith which protrudes at the summit and can clearly be seen from the lowlands, said to be the home of its masculine enchanter-protector, Asog.",
    location: "Macabugos, Libon, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "51",
    name: "SILAY CAVE 2",
    image: "https://source.unsplash.com/1000x700/?SILAY%20CAVE%202",
    description: "Located at Brgy. Quitinday, 1km from the poblacion town and about 200 meters from the Jovellar Underground River and 200 meters from Silay Cave 1. This cave served as the guerillas’ hideout during the Japanese War (1937-1945).",
    location: "Quitinday, Jovellar, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "52",
    name: "Bantigue Coves and Rock Formations",
    image: "https://source.unsplash.com/1000x700/?Bantigue%20Coves%20and%20Rock%20Formations",
    description: "Located Libon's coastline, Bantigue is frequented by tourists to see its marine rocks formations, crystal-clear waters and cozy lagoons. It has pebble-sand beaches and well-preserved coral reefs, being part of Libon's marine protected area and fish sanctuary and marine reserve (FSMR).",
    location: "Talin-Talin, Libon, Albay",
    category: "Coastal Landscape and Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "53",
    name: "QUE MOLAR CAVE",
    image: "https://source.unsplash.com/1000x700/?QUE%20MOLAR%20CAVE",
    description: "located at Brgy. Quitinday, 1km from the poblacion town. It has complicated entrance with plenty of rock chambers. Only medium sized individuals could pass through the tight entrance with the assistance of other companions. It has spacious interior with variety of rock formations.",
    location: "Quitinday, Jovellar, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "54",
    name: "SAGAMA CAVE",
    image: "https://source.unsplash.com/1000x700/?SAGAMA%20CAVE",
    description: "Located at Brgy. Quitinday, 1 km from the poblacion town and about 200 meters north of the holding areas. Rubbles can be seen, believed to be evidence of past erosion.  Large quantities of limestone rock deposits are observed.",
    location: "Quitinday, Jovellar, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "55",
    name: "CATTLE CAVE",
    image: "https://source.unsplash.com/1000x700/?CATTLE%20CAVE",
    description: "located at Brgy. Quitinday, 1 km from the poblacion town, the nearest cave to the holding area merely 100 meters above. It has low entrance, you’ll partly crawl when entering the cave. The inner part of the cave measures about 6 feet tall and is maintained throughout the span of the cave.",
    location: "Quitinday, Jovellar, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "56",
    name: "Trinity Island",
    image: "https://source.unsplash.com/1000x700/?Trinity%20Island",
    description: "A group of low-lying hills surrounding the gentle valleys along the coast in rural Albay; a pebbly, sandy shore, a boscage of lush trees, a blue lagoon, fishing boat that seem to have become part of the landscape.",
    location: "Cagmanaba, Oas, Albay",
    category: "Coastal Landscape and Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "57",
    name: "CATTLE CAVE EXTREME",
    image: "https://source.unsplash.com/1000x700/?CATTLE%20CAVE%20EXTREME",
    description: "Located at Brgy. Quitinday, 1 km from the poblacion town and 35 meters from the holding area. This is a tunnel-shaped cave with a stretch of more or less 700 meters. One has to crawl to go through the inner-most part of the cave.",
    location: "Quitinday, Jovellar, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "58",
    name: "Mount Lanagan Sea of Clouds",
    image: "https://source.unsplash.com/1000x700/?Mount%20Lanagan%20Sea%20of%20Clouds",
    description: "Libon’s highest elevation, Mt. Lanagan has several caves, two mountain lakes, and a panoramic view of Burias Pass and areas of Albay and Cam Sur. Cottages are offered at the summit relaxation of campers or hikers. Visitors who spend the night at the summit can witness sea of clouds during dawn.",
    location: "Caguscos, Libon, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "59",
    name: "Rawis Sandbar",
    image: "https://source.unsplash.com/1000x700/?Rawis%20Sandbar",
    description: "This baura is a 232-hectare sandbar which, during low tides and full moons, visitors could skin dive, spot sea creatures such as starfishes and sea urchins, and walk on white sand, at the middle of the sea! It is located at Libon’s protected fish sanctuary and marine reserve off the coast of Rawis.",
    location: "Rawis, Libon, Albay",
    category: "Coastal Landscape and Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "60",
    name: "Buga Lake",
    image: "https://source.unsplash.com/1000x700/?Buga%20Lake",
    description: "Libon’s share of Bato Lake is a major fishing zone in the municipality. Aside from boating and fishing, visitors are provided an amazing view of some of Bicol’s prominent mountains including the Mayon Volcano, Mount Masaraga, Mount Iriga and Mount Malinao.",
    location: "Buga, Libon, Albay",
    category: "Lakes and Pond",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "61",
    name: "Bambusetum",
    image: "https://source.unsplash.com/1000x700/?Bambusetum",
    description: "a two-hectare bamboo plantation adjacent to Kawa-Kawa, lushed with a variety of bamboo species. Different kinds of flowering plants are also found in the scenic site.",
    location: "Tuburan, Ligao City, Albay",
    category: "Other Natural Attractions (e.g. century old trees/forest, endemic species)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "62",
    name: "Buhawi Hill Camping Site",
    image: "https://source.unsplash.com/1000x700/?Buhawi%20Hill%20Camping%20Site",
    description: "Buhawi Hill Camping Site is found in the beautiful Municipaity of Pioduran. The Camping Site offers an outdoor activities where a group of people spends time with nature, far away from the City. The hill has an approximately 330 meters above sea level.",
    location: "Panganiran, Pio Duran, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "63",
    name: "Kawa Kawa Natural Park",
    image: "https://source.unsplash.com/1000x700/?Kawa%20Kawa%20Natural%20Park",
    description: "Dubbed as the “hill without a hill top”, Kawa Kawa Natural Park is visited by an average of 600,000 tourists every year. Its cauldron-like shape with Stations of the Cross lining around the hill is famous for the life-size statues depicting the Passion of Christ.",
    location: "Tuburan, Ligao City, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "64",
    name: "The Campsite",
    image: "https://source.unsplash.com/1000x700/?The%20Campsite",
    description: "The first tourist attraction developed in Mt. Masaraga. With its perfect location, fronting the incomparable beauty of Mt. Mayon, it has become very popular to people who love nature, like campers, trekkers and adventurers.",
    location: "Amtic, Ligao City, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "65",
    name: "Gogongon Falls",
    image: "https://source.unsplash.com/1000x700/?Gogongon%20Falls",
    description: "Gogongon Falls sits on a high cliff draining its water in a deep lagoon ideal for swimming. The river bed going to the falls is like a cemented road which crystal-clear waters swiftly flowing. It takes more than one hour of walking along greeneries and several small falls are found along the way.",
    location: "Harigue, Libon, Albay",
    category: "Falls",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "66",
    name: "Paayahayan sa Bulod",
    image: "https://source.unsplash.com/1000x700/?Paayahayan%20sa%20Bulod",
    description: "As Mt. Masaraga became a popular tourist destination in Bicol, Paayahayan Sa Bulod soon emerged as a captivating tourist attraction in the site. It has a wide area enough to home various species of ornamental and flowering plants.",
    location: "Amtic, Ligao City, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "67",
    name: "Hobbit Hill",
    image: "https://source.unsplash.com/1000x700/?Hobbit%20Hill",
    description: "Has a refreshing scenic site, with a great view of Bicol’s pride, Mt. Mayon. Its perfect location is a good point that attracts many tourists with the thought that Hobbit attracts many tourists wherein one could mistake hobbit as found or located outside the country.",
    location: "Amtic, Ligao City, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "68",
    name: "Balinsasayawan Cave",
    image: "https://source.unsplash.com/1000x700/?Balinsasayawan%20Cave",
    description: "Named after the swiftlets, Balinsasayawan cave sits on a mountain slope and its top-most part serves as a view deck overlooking Libon- Polangui, Bato Lake and Buhi Mountain Lake. The cave interior is big and wide with cool air soothing the skin and is abundant in stalagmites and stalactites.",
    location: "San Ramon, Libon, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "69",
    name: "Mt. Masaraga",
    image: "https://source.unsplash.com/1000x700/?Mt.%20Masaraga",
    description: "The third of the three beautiful mountains comprising the Magayon Trio in Albay.  The newest sports tourism site in Ligao City with a breath-taking and scenic trails makes it one of the most exciting and fast-growing destinations just perfect for those who love adventures in the Bicol Region.",
    location: "Amtic, Ligao City, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "70",
    name: "Tagas Falls",
    image: "https://source.unsplash.com/1000x700/?Tagas%20Falls",
    description: "These mutual falls at Pantao is a little paradise with blue water lagoon hidden in a virgin rain forest. The water cascading from the water falls goes deep down to a clear lagoon. The site is 40 minutes travel from Poblacion Libon, Albay and 20 minutes walk from Barangay Proper (Balyena Street).",
    location: "Pantao, Libon, Albay",
    category: "Falls",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "71",
    name: "Cañeta and Mararag Falls",
    image: "https://source.unsplash.com/1000x700/?Cañeta%20and%20Mararag%20Falls",
    description: "Considered as hidden gems of San Jose, these mutual falls are an hour away from the barangay proper. Mararag falls is vertically measured at 35 feet while Cañeta falls is 25 feet.",
    location: "San Jose, Libon, Albay",
    category: "Falls",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "72",
    name: "Tambac Beach Resorts",
    image: "https://source.unsplash.com/1000x700/?Tambac%20Beach%20Resorts",
    description: "The Beach Resorts of Ligao have pristine swimming opportunities waiting to greet you! The 8-kilometer-long stretch of powdery, almost-white sand, and sparkling blue waters welcomes divers and snorkelers to enjoy, discover its beauty and revel in the delightful coral reefs.",
    location: "Maonon, Ligao City, Albay",
    category: "Coastal Landscape and Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "73",
    name: "Batong Languyon",
    image: "https://source.unsplash.com/1000x700/?Batong%20Languyon",
    description: "It is an islet of natural rock formation located in the coastal area of Ligao. In the waters surrounding the rock islet, divers can see at a depth of 80 feet, with a variety of beautiful coral reefs, and marine species.",
    location: "Maonon, Ligao City, Albay",
    category: "Coastal Landscape and Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "74",
    name: "Mangrove Plantation",
    image: "https://source.unsplash.com/1000x700/?Mangrove%20Plantation",
    description: "A 42-hectare plantation with thousands mangrove propagules planted since 2008. This was initiated to advocate for marine biodiversity protection and preservation of environmental resources to sustain livelihood for the coastal communities.",
    location: "Cabarian, Ligao City, Albay",
    category: "Unique Natural Landscape / Seascape",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "75",
    name: "Camp One Tree Hill",
    image: "https://source.unsplash.com/1000x700/?Camp%20One%20Tree%20Hill",
    description: "It is a potential tourism attraction with a panoramic view of rolling hills similar to chocolate hills in Bohol. You will be delighted to see the magnificent beauty of Mt. Mayon and Mt. Masaraga.  Visit this place where you can recharge and energize your tired body and soul.",
    location: "Macalidong, Ligao City, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "76",
    name: "Mayon Volcano Natural Park",
    image: "https://source.unsplash.com/1000x700/?Mayon%20Volcano%20Natural%20Park",
    description: "The perfect getaway, Nature and Adventure, here you can go Trekking, explore new terrain for Down Hill Mountain Biking and see the Enchanted Centennial tree at the heart of MVNP.",
    location: "Lidong, Santo Domingo, Albay",
    category: "Other Natural Attractions (e.g. century old trees/forest, endemic species)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "77",
    name: "Inang Maharang Mud Pool",
    image: "https://source.unsplash.com/1000x700/?Inang%20Maharang%20Mud%20Pool",
    description: "Located in Sitio Inang-Maharang, Barangay Nagotgot, Manito, Albay is the Inang-Maharang Mud Pool which is typically a volcanic geyser. This Mud Pool scattered small wells oozing sulfuric smell and is an abundant source of mud pack.",
    location: "Sitio Inang Maharang Brgy. Nagotgot, Manito, Albay",
    category: "Lakes and Pond",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "78",
    name: "Mangrove Forest",
    image: "https://source.unsplash.com/1000x700/?Mangrove%20Forest",
    description: "Mangrove Forest are important ecosystem so we should care about Mangroves because they give Biodiversity by providing a nesting and breeding area for fish and shellfish, with these it gives livelihood to the people, maintain water quality, coastal defense and fight climate change.",
    location: "Buhatan, Santo Domingo, Albay",
    category: "Other Natural Attractions (e.g. century old trees/forest, endemic species)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "79",
    name: "Manilao Cave",
    image: "https://source.unsplash.com/1000x700/?Manilao%20Cave",
    description: "Named after the \"Anilao\" tree, which was abundant in the area, the cave is classified Class II by the DENR. Although the cave is good for tourism, portion of it is restricted. The cave is still unexplored by tourist.",
    location: "BInanderahan, Camalig, Albay",
    category: "Caves (inland)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "80",
    name: "Ligñon Hill",
    image: "https://source.unsplash.com/1000x700/?Ligñon%20Hill",
    description: "Experience Ligñon Hill with its breathtaking 360-degree view of the city at its famous view deck on the hill top.",
    location: "Bogtong, Legazpi City, Albay",
    category: "Mountains / Hills / Highlands",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "81",
    name: "PHILCERAMICS",
    image: "https://source.unsplash.com/1000x700/?PHILCERAMICS",
    description: "The PHILCERAMICS is a shared service facility which aims to propel the development of terra-cotta industry. The pottery and ceramic industry is a century old industry in Putsan, Tiwi, Albay and is the primary livelihood of the community. Coron is Tiwi's \"One Town One Product\"",
    location: "Putsan, Tiwi, Albay",
    category: "Other Historical or Cultural Attractions",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "82",
    name: "Plaza del Cristo Rey",
    image: "https://source.unsplash.com/1000x700/?Plaza%20del%20Cristo%20Rey",
    description: "Centuries old plaza that forms a part of the Saint John the Baptist Church.",
    location: "San Juan, Tabaco City, Albay",
    category: "Structures and Buildings",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "83",
    name: "Saint Michael the Archangel Parish Church",
    image: "https://source.unsplash.com/1000x700/?Saint%20Michael%20the%20Archangel%20Parish%20Church",
    description: "A Roman Catholic church in Oas, Albay, which consists of the main church structure adjoining a bell tower on one side and a parish house on the other.",
    location: "Iraya Norte, Oas, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "84",
    name: "OUR LADY OF ASSUMPTION PARISH",
    image: "https://source.unsplash.com/1000x700/?OUR%20LADY%20OF%20ASSUMPTION%20PARISH",
    description: "Church",
    location: "Poblacion, Guinobatan, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "85",
    name: "Our Lady of Mt. Carmel Parish",
    image: "https://source.unsplash.com/1000x700/?Our%20Lady%20of%20Mt.%20Carmel%20Parish",
    description: "Our Lady of Mt. Carmel Parish has been declared as a national historical and cultural property recognized by the local government. It was built on 1877 after 88 years of construction.",
    location: "Barangay 2 & 5, Malilipot, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "86",
    name: "MUSEO de GUINOBATAN",
    image: "https://source.unsplash.com/1000x700/?MUSEO%20de%20GUINOBATAN",
    description: "museum",
    location: "Iraya, Guinobatan, Albay",
    category: "Museum",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "87",
    name: "St. John the Baptist Church",
    image: "https://source.unsplash.com/1000x700/?St.%20John%20the%20Baptist%20Church",
    description: "One of the town's significant heritage structures. Declared by the NHCP as Levell II heritage structure with historical marker and Important Cultural Property by the National Museum.",
    location: "Barangay 2, Camalig, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "88",
    name: "Cluster of Colonial Houses",
    image: "https://source.unsplash.com/1000x700/?Cluster%20of%20Colonial%20Houses",
    description: "Old Houses located in the Camalig Old Pueblo that bear high historical significance, built during the Spanish and American period, once owned by the prominent families that served as the leaders of the town and the province.",
    location: "Barangays 5 and 7, Camalig, Albay",
    category: "Structures and Buildings",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "89",
    name: "St. John the Baptist Parish Church",
    image: "https://source.unsplash.com/1000x700/?St.%20John%20the%20Baptist%20Parish%20Church",
    description: "The Parish Church of San Juan Bautista Tabaco Albay was declared as one of the Albay's four national treasures.",
    location: "San Juan, Tabaco City, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "90",
    name: "Hoyop-hoyopan Cave",
    image: "https://source.unsplash.com/1000x700/?Hoyop-hoyopan%20Cave",
    description: "Approximately situated 10 kms. from the Poblacion (Camalig Town Center and 7 kms. from the BIA, the nearest gateway. Pottery, human bones, beadwork and artifacts believed to be 4,000 years old have been unearthed from these caves.",
    location: "Barangay Cotmon, Camalig, Albay",
    category: "Archaeological / Historic Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "91",
    name: "Bahay-Kalakal ni Smith, Bell & Company",
    image: "https://source.unsplash.com/1000x700/?Bahay-Kalakal%20ni%20Smith,%20Bell%20&%20Company",
    description: "The Spanish-era structure of durable stone & delicate capiz was once the office of an import-export firm dealing in abaca whose origins dated from 1868. This company house was owned by a talented poetess named Angela Manalang-Gloria.",
    location: "Cormidal, Tabaco City, Albay",
    category: "Structures and Buildings",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "92",
    name: "St. Lawrence the Martyr Parish Church",
    image: "https://source.unsplash.com/1000x700/?St.%20Lawrence%20the%20Martyr%20Parish%20Church",
    description: "St. Lawrence the Martyr Parish Church was built in 1829 and became the parish church of Tiwi in 1863 after it was dedicated to St. Lawrence the Martyr.",
    location: "Tigbi, Tiwi, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "93",
    name: "Tabaco Catholic Cemetery Cimburrio",
    image: "https://source.unsplash.com/1000x700/?Tabaco%20Catholic%20Cemetery%20Cimburrio",
    description: "The chapel was built in 1861 with a combination of medieval & baroque architecture which was patterned after the structural design of St. John the Baptist Church.",
    location: "Tagas, Tabaco City, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "94",
    name: "Our Lady of Salvacion Parish Church",
    image: "https://source.unsplash.com/1000x700/?Our%20Lady%20of%20Salvacion%20Parish%20Church",
    description: "One of the Pilgrim destinations in the Province of Albay, The Church houses the Image of Our Lady of Salvation, which is the Diocesan Patroness of Albay. It was declared a Diocesan Shrine in 1976 after the canonical coronation of Our Lady of Salvation by Jaime Cardinal Sin.",
    location: "Joroan, Tiwi, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "95",
    name: "Ligao City Heritage Library and Museum",
    image: "https://source.unsplash.com/1000x700/?Ligao%20City%20Heritage%20Library%20and%20Museum",
    description: "It's a one stop Research and Resource center that houses contemporary and rare reading materials on Philippine Arts, Language, Religion, History and Culture among many others. Also found are vintage periodicals, photographs, memorabilia and maps of Ligao City.",
    location: "Dunao, Ligao City, Albay",
    category: "Museum",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "96",
    name: "The Fallen Sons of Ligao",
    image: "https://source.unsplash.com/1000x700/?The%20Fallen%20Sons%20of%20Ligao",
    description: "This is one of Ligao City’s most important landmarks. The monument with the names of the war veterans engraved on it reminds the Ligaoenos of their fallen heroes who sacrificed their lives for freedom. It is now considered a must in every tourist and visitor’s itinerary.",
    location: "Dunao, Ligao City, Albay",
    category: "Historic Monuments",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "97",
    name: "St. Stephen Protomartyr Parish Church",
    image: "https://source.unsplash.com/1000x700/?St.%20Stephen%20Protomartyr%20Parish%20Church",
    description: "– Ligao is indeed gifted with both natural and historical riches. St. Stephen the Proto-martyr Parish is one of the 17th century churches and is among the greatest landmarks of Albay. It is one of the city’s best and proudest attractions as it bridges the past to the present.",
    location: "Guilid, Ligao City, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "98",
    name: "Sts. Joachim and Anne Church",
    image: "https://source.unsplash.com/1000x700/?Sts.%20Joachim%20and%20Anne%20Church",
    description: "Sts. Joachim and Anne Parish Church is built in the year 1600 during the Spaniards colonization of the country. It was damaged during the 1766 Mayon Volcano eruption and later rebuilt.",
    location: "Poblacion, Malinao, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "99",
    name: "Libon Flaming Water",
    image: "https://source.unsplash.com/1000x700/?Libon%20Flaming%20Water",
    description: "Located at Libon Central School, the flaming water was accidentally-discovered by its school janitor in 1962. When he lighted a cigarette, he threw the matchstick into a pond and alas, the water suddenly burst into flames! Today, it is housed in a facility that harnesses energy used for cooking.",
    location: "Zone II, Libon, Albay",
    category: "Other Historical or Cultural Attractions",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "100",
    name: "Saint James the Greater Parish Church and Relics of Santiago el Mayor",
    image: "https://source.unsplash.com/1000x700/?Saint%20James%20the%20Greater%20Parish%20Church%20and%20Relics%20of%20Santiago%20el%20Mayor",
    description: "Declared as a pilgrim church for the celebration of 300 YOC, the St. James the Greater Parish Church reminds visitors of Libon’s opulent past as one of the only eight villas in the country, and of its role in the propagation of Christianity in Bicol during the Spanish occupation of the country.",
    location: "Zone III, Libon, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "101",
    name: "Oas Bell Tower",
    image: "https://source.unsplash.com/1000x700/?Oas%20Bell%20Tower",
    description: "In 1825, a church of rock and stones was built that was reconstructed in 1866 after being razed by fire.",
    location: "Iraya Norte, Oas, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "102",
    name: "Rizal Park",
    image: "https://source.unsplash.com/1000x700/?Rizal%20Park",
    description: "The monument was built in 1955. It shows Rizal in his usual overcoat with his book in his left. The monument in the town plaza of Oas is a model of simplicity.",
    location: "Iraya Norte, Oas, Albay",
    category: "Historic Monuments",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "103",
    name: "Divine Mercy Shrine and Monastery of the Carmelite Nuns of the Holy Trinity",
    image: "https://source.unsplash.com/1000x700/?Divine%20Mercy%20Shrine%20and%20Monastery%20of%20the%20Carmelite%20Nuns%20of%20the%20Holy%20Trinity",
    description: "It serves as a Pilgrim Center of Ligao City drawing in visitors from different places in the country. The shrine has a columbary and a wide staircases bearing the footprints and handprints of the Shrine’s visitors and devotees.",
    location: "Tuburan, Ligao City, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "104",
    name: "Miguel Lopez de Legazpi Monument",
    image: "https://source.unsplash.com/1000x700/?Miguel%20Lopez%20de%20Legazpi%20Monument",
    description: "Also known as El Adelantado and El Viejo (The Elder). Was a Basque-Spanish navigator and governor who established the first Spanish settlement in the East Indies when his expedition crossed the Pacific Ocean.",
    location: "Brgy. Dap-Dap, Legazpi City, Albay",
    category: "Historic Monuments",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "105",
    name: "The Obelisk",
    image: "https://source.unsplash.com/1000x700/?The%20Obelisk",
    description: "The first-ever obelisk built and instituted in the entire Southern Luzon and of the whole Luzon Island with 13.1 feet in height.",
    location: "Puro, Legazpi City, Albay",
    category: "Historic Monuments",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "106",
    name: "Battle of Legazpi Memorial Pylon",
    image: "https://source.unsplash.com/1000x700/?Battle%20of%20Legazpi%20Memorial%20Pylon",
    description: "It is a memorial to the valiant defense of Albayanos against American invaders in 1900. Located at the heart of Central Business District of the City.",
    location: "Brgy. Capantawan, Legazpi City, Albay",
    category: "Historic Monuments",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "107",
    name: "Headless Monument",
    image: "https://source.unsplash.com/1000x700/?Headless%20Monument",
    description: "Constructed as a dedication to the unknown heroes who died and shed their blood during the Japanese military occupation in Legazpi City",
    location: "Brgy. Lapu-Lapu, Legazpi City, Legazpi City, Albay",
    category: "Historic Monuments",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "108",
    name: "St. Dominic Church",
    image: "https://source.unsplash.com/1000x700/?St.%20Dominic%20Church",
    description: "First Church Built: 1749, in 1850 The old Church roof of basag (split bamboo) was burned to ashes to ashes, hence the transfer of the service to the present church, which was nearing completion under the direction of D. Martin Martinez.",
    location: "Market Site, Santo Domingo, Albay",
    category: "Church, Mosque, Temples or other Religious Sites",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "109",
    name: "General Ignacio Paua Monument",
    image: "https://source.unsplash.com/1000x700/?General%20Ignacio%20Paua%20Monument",
    description: "The only pure-blooded Chinese general who supported the Katipuneros in the fight against the Spaniards.",
    location: "Banadero, Legazpi City, Albay",
    category: "Historic Monuments",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "110",
    name: "Pugad Lawin Park",
    image: "https://source.unsplash.com/1000x700/?Pugad%20Lawin%20Park",
    description: "Constructed: 1926-1927 1st in Bicol Initiated by: Diego Balin together with the revolutionary Veteran. Here also lies the remains of Potenciano V. Gregorio the composer of the beloved song of Bicol SARUNG BANGGI. Composed one dark night in 1910 in the little town of Libog at the foot of Mayon.",
    location: "Poblacion, Santo Domingo, Albay",
    category: "Historic Monuments",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "111",
    name: "Ibalong Heroes Monument",
    image: "https://source.unsplash.com/1000x700/?Ibalong%20Heroes%20Monument",
    description: "An honor to the three Ibalong mythical heroes namely Baltog, Handyong and Bantong, for the bravery they have exemplified",
    location: "Lapu-Lapu, Legazpi City, Albay",
    category: "Historic Monuments",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "112",
    name: "Padang Memorial Shrine",
    image: "https://source.unsplash.com/1000x700/?Padang%20Memorial%20Shrine",
    description: "Repository shrine in memory of the residents of Padang who died during Typhoon Reming",
    location: "Padang, Legazpi City, Albay",
    category: "Historic Monuments",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "113",
    name: "Albay Gulf Landing Commemorative Pylon",
    image: "https://source.unsplash.com/1000x700/?Albay%20Gulf%20Landing%20Commemorative%20Pylon",
    description: "Built in 1995 in connection with the 50th Anniversary of the Landing of the Allied American Forces in Legazpi City, which led to the City's liberation from the Japanese occupation forces",
    location: "Rawis, Legazpi City, Albay",
    category: "Historic Monuments",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "114",
    name: "Tabaco City Presidencia Building",
    image: "https://source.unsplash.com/1000x700/?Tabaco%20City%20Presidencia%20Building",
    description: "This near century-old structure which was completed in 1929, serves as Tabaco's civil government center since the American period - responsible for catering to the social need and providing government services to the public.",
    location: "Quinale, Tabaco City, Albay",
    category: "Structures and Buildings",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "115",
    name: "Tabaco City Material Recovery Facility (MRF)",
    image: "https://source.unsplash.com/1000x700/?Tabaco%20City%20Material%20Recovery%20Facility%20(MRF)",
    description: "Facility owned by the City Government of Tabaco where recyclable and biodegradable materials are turned into reusable products like eco-bricks and natural composts.",
    location: "San Vicente, Tabaco City, Albay",
    category: "Industrial Facilities (e.g. Gov't flagship facilities like model recycling centers)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "116",
    name: "Pandayan sa Cobo",
    image: "https://source.unsplash.com/1000x700/?Pandayan%20sa%20Cobo",
    description: "Barangay Cobo is the Home of great blacksmiths in Tabaco City. Tabak-making is a labor-intensive craft forging world-class cutlery products.",
    location: "Cobo, Tabaco City, Albay",
    category: "Arts and Craft",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "117",
    name: "Villa Miranda Farm and Resort (Grapes Farm)",
    image: "https://source.unsplash.com/1000x700/?Villa%20Miranda%20Farm%20and%20Resort%20(Grapes%20Farm)",
    description: "The Home of Grapes in the South, Villa Miranda Farm and Resort is the first vineyard in the Bicol Region that harvests locally-grown red cardinal grapes. It houses a mushroom farm and a vegetable terraces. Located at Macabugos, VMFR is a DOT-accredited farm site owned by the Sasutona family.",
    location: "Macabugos, Libon, Albay",
    category: "Farm / Ranch",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "118",
    name: "Brizuela Natural Farm",
    image: "https://source.unsplash.com/1000x700/?Brizuela%20Natural%20Farm",
    description: "Private diversified farming that can be used as a study tour for farmers and farming enthusiasts.",
    location: "Tabiguian, Tabaco City, Albay",
    category: "Farm / Ranch",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "119",
    name: "Mirisbiris Garden and Nature Center",
    image: "https://source.unsplash.com/1000x700/?Mirisbiris%20Garden%20and%20Nature%20Center",
    description: "A hobbyist botanical garden, with medical and kitchen herbs, and organic tropical fruits and veggies. Rainforest to coral reefs. B&B, coffe shop. Welcome!",
    location: "Salvacion, Santo Domingo, Albay",
    category: "Farm / Ranch",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "120",
    name: "Sto. Domingo Handicraft",
    image: "https://source.unsplash.com/1000x700/?Sto.%20Domingo%20Handicraft",
    description: "A place where the design are carefully hand crafted by the Domingueño workers, most of it are Wall Frames, Picture and Certificate Frames, Office and Chocolate Boxes, Sashes, Trophies and other personalized design.",
    location: "San Juan St., Santo Domingo, Albay",
    category: "Arts and Craft",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "121",
    name: "Tabaco City Plaza",
    image: "https://source.unsplash.com/1000x700/?Tabaco%20City%20Plaza",
    description: "A converging point for huge crowds during important activities of the city.",
    location: "Quinale, Tabaco City, Albay",
    category: "Parks",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "122",
    name: "Parong Bermuda Resort",
    image: "https://source.unsplash.com/1000x700/?Parong%20Bermuda%20Resort",
    description: "Located in Sitio Parong Brgy Pawa Manito Albay is where you can find Parong Bermuda Resort that offers a Homestay accommodation. This property offers a private pool and free private parking.",
    location: "Pawa, Manito, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "123",
    name: "Victoria Bay Resort",
    image: "https://source.unsplash.com/1000x700/?Victoria%20Bay%20Resort",
    description: "Beach and pool that offers overnight accommodation, meals, watersports activities and other services",
    location: "Cagmanaba, Oas, Albay",
    category: "Water Sports (Excludes Diving, see Nature Category)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "124",
    name: "Magayon Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Magayon%20Beach%20Resort",
    description: "Located in Brgy Malobago Manito, Albay is where you can find Magayon Beach Resortt. This private property offers a private pool and is also accessible by land and is an hour away from the City of Legazpi.",
    location: "Malobago, Manito, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "125",
    name: "Sabando- Ocampo Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Sabando-%20Ocampo%20Beach%20Resort",
    description: "Beach and pool that offers overnight accommodation, meals and watersports activities and other services",
    location: "Maramba, Oas, Albay",
    category: "Water Sports (Excludes Diving, see Nature Category)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "126",
    name: "3 Star Kids Resort",
    image: "https://source.unsplash.com/1000x700/?3%20Star%20Kids%20Resort",
    description: "Located in Sitio Sua Brgy Cabit Manito, Albay is whereyou can find 3 Star Kids Farm and Resort. This property offers a private pool and free private parking.",
    location: "Cabit, Manito, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "127",
    name: "D'Beach Camp",
    image: "https://source.unsplash.com/1000x700/?D'Beach%20Camp",
    description: "Located in Brgy Cawit Manito, Albay is where you can find D’Beach Camp. An emerging adventure destination that offers different activities.",
    location: "Cawit, Manito, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "128",
    name: "Palacio Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Palacio%20Beach%20Resort",
    description: "Indulge in nature tripping, island hopping, kayaking or just splash in clear water. They offer day and night tour. Transportation may be arranged upon request. Small function hall is available in any occasion",
    location: "Cagmanaba, Oas, Albay",
    category: "Beach for Sea Bathing",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "129",
    name: "Cagraray Eco-Energy Park",
    image: "https://source.unsplash.com/1000x700/?Cagraray%20Eco-Energy%20Park",
    description: "The Cagraray Eco-Energy Park, nestled in the island paradise of Cagraray in Bacacay, Albay, is the premier ecological park in Bicol Region that welcomes you to a world of environmental education, passive recreations, extreme adventure sports, and various ecological activities.",
    location: "Misibis, Bacacay, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "130",
    name: "TNHS Lagman Gymnasium",
    image: "https://source.unsplash.com/1000x700/?TNHS%20Lagman%20Gymnasium",
    description: "A gymnasium built within Tabaco National High School premises where events and gatherings are conducted",
    location: "Panal, Tabaco City, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "131",
    name: "BUTC Lagman Auditorium",
    image: "https://source.unsplash.com/1000x700/?BUTC%20Lagman%20Auditorium",
    description: "A gymnasium built within the Bicol University Tabaco Campus where",
    location: "Tayhi, Tabaco City, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "132",
    name: "Palali Eco Farm and Spring Resort",
    image: "https://source.unsplash.com/1000x700/?Palali%20Eco%20Farm%20and%20Spring%20Resort",
    description: "Located at Sitio Malangto Brgy. Nagotgot Mnaito Albay is where you can find Palali Eco Farm and Spring Resort. A resort perfect for Family and friends bonding. Fresh running water right from \"bukal\" as locals says.",
    location: "Nagotgot, Manito, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "133",
    name: "Casa Ver Amore",
    image: "https://source.unsplash.com/1000x700/?Casa%20Ver%20Amore",
    description: "Italian/Roman influenced venue place that can hold five hundred to one thousand individuals for gatherings.",
    location: "Bombon, Tabaco City, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "134",
    name: "Kayla & Carly Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Kayla%20&%20Carly%20Beach%20Resort",
    description: "Beach resort Homestay",
    location: "Tapel, Oas, Albay",
    category: "Beach for Sea Bathing",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "135",
    name: "Hiraya Manawari Nature Park",
    image: "https://source.unsplash.com/1000x700/?Hiraya%20Manawari%20Nature%20Park",
    description: "Once an empty parcel of land located within the city MRF, was transformed into a nature park using upcycled trash. Hiraya Manawari Nature Park was built through the individual aspirations and collective efforts of the City Government employees of Tabaco.",
    location: "San Vicente, Tabaco City, Albay",
    category: "Leisure Land, Theme Park",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "136",
    name: "Attorney's Beach Place",
    image: "https://source.unsplash.com/1000x700/?Attorney's%20Beach%20Place",
    description: "Attorney's Beach Place (ABP) is a private resort located at Rawis, Libon, Albay. It is a place suited for people who wish to enjoy and relax with nature together with their families, friends, and loved ones. It offers cove hopping, boating and other sea adventures.",
    location: "Rawis, Libon, Albay",
    category: "Beach for Sea Bathing",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "137",
    name: "Banago Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Banago%20Beach%20Resort",
    description: "In the deep of Sto. Domingo, Albay lies a peaceful haven where you can relax and enjoy all the aqua sports they are offering.",
    location: "Alimsog, Santo Domingo, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "138",
    name: "Barrios' Kids Pool",
    image: "https://source.unsplash.com/1000x700/?Barrios'%20Kids%20Pool",
    description: "Barrios'kids' Pool is located at the foot of Mayon Volcano facing the Albay gulf. The resort has 7 pools, it has the coolest and cleanest water spring source.",
    location: "San Juan St., Santo Domingo, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "139",
    name: "Sarung Banggi Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Sarung%20Banggi%20Beach%20Resort",
    description: "Great place to relax and enjoy",
    location: "San Vicente St., Santo Domingo, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "140",
    name: "Legazpi Boulevard",
    image: "https://source.unsplash.com/1000x700/?Legazpi%20Boulevard",
    description: "Well-known as the \"Fitness Hub of the City\". The Legazpi Boulevard extension is a scenic 4.095 kilometer seaside road that takes advantage of  the panoramic view of the azure Albay Gulf, the Kapuntukan Hill (Sleeping Lion) and the surrounding islands.",
    location: "Dap-Dap, Legazpi City, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "141",
    name: "Puerto Vista Resort",
    image: "https://source.unsplash.com/1000x700/?Puerto%20Vista%20Resort",
    description: "We cater weddings, corporate events, seminars, debut, conference, baptismal, parties and other social gatherings.",
    location: "Del Rosario, Santo Domingo, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "142",
    name: "Don Bitoy Resort and Catering Services",
    image: "https://source.unsplash.com/1000x700/?Don%20Bitoy%20Resort%20and%20Catering%20Services",
    description: "Hotel Resort and Lodging",
    location: "San Isidro, Santo Domingo, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "143",
    name: "Costa Palmera Resort",
    image: "https://source.unsplash.com/1000x700/?Costa%20Palmera%20Resort",
    description: "A simple paradise carved on the shores of Mount Mayon. 24hour room service. Open on all holidays.",
    location: "Calayucay, Santo Domingo, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "144",
    name: "OHH LALA PARADISE SPRING RESORT",
    image: "https://source.unsplash.com/1000x700/?OHH%20LALA%20PARADISE%20SPRING%20RESORT",
    description: "Oh la la paradise spring resort is a beautiful hidden paradise deep inside Guinobatan, Albay, Spring-water swimming pools with waterpark, clean, beautifully landscaped grounds and a host of leisure activities,  OH LA LA is a perfect refuge to relax and is true to its unique name",
    location: "Muladbucad Grande, Guinobatan, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "145",
    name: "Ligao City Park",
    image: "https://source.unsplash.com/1000x700/?Ligao%20City%20Park",
    description: "The plaza as beautifully dressed in Disney theme during Christmas Season is a favorite place for people on special occasions and for their daily social interactions. At the park also stands Dr. Jose P. Rizal’s proud monument. The fountain with lights changing color is an added attraction.",
    location: "Sta. Cruz, Ligao City, Albay",
    category: "Parks",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "146",
    name: "MAYON GARDEN RESORTS & HOTEL",
    image: "https://source.unsplash.com/1000x700/?MAYON%20GARDEN%20RESORTS%20&%20HOTEL",
    description: "MAYON GARDEN is a Nature-inspired Paradise Resort that lies on the foot of Glorious Mayon Volcano in Albay, Philippines.",
    location: "Masarawag, Guinobatan, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "147",
    name: "PAY TONIO'S MOUNTAIN RESORT",
    image: "https://source.unsplash.com/1000x700/?PAY%20TONIO'S%20MOUNTAIN%20RESORT",
    description: "An agri-farm and resort. The sanctuary of peace, recreation and happiness.",
    location: "Maguiron, Guinobatan, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "148",
    name: "Don Manuel Rendezvouz Resort",
    image: "https://source.unsplash.com/1000x700/?Don%20Manuel%20Rendezvouz%20Resort",
    description: "Don Manuel Rendezvous Resort –Introduced the first wave pool in Albay. The resort offers several activities to its customers and guests. It also has room accommodation for those who want to stay overnight or those who prefer to occupy room for their comfort.",
    location: "Herrera, Ligao City, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "149",
    name: "Ligao Hidden Spring Resort",
    image: "https://source.unsplash.com/1000x700/?Ligao%20Hidden%20Spring%20Resort",
    description: "It is a natural cold spring resort beautifully settled in Brgy Herrera, Ligao City. The pool has cold water coming from a strong spring source and attracts visitors who love  nature and looking for a budget-friendly nice spot to enjoy and relax especially during summer season.",
    location: "Herrera, Ligao City, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "150",
    name: "D' HACIENDA RESORT",
    image: "https://source.unsplash.com/1000x700/?D'%20HACIENDA%20RESORT",
    description: "Everyone who has visited this place has only one common thing to say:\" It's Paradise!\" Come & experience the vastness of nature in this 15-hectare place!",
    location: "Quibongbongan, Guinobatan, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "151",
    name: "FRANCIA PRIVATE POOL",
    image: "https://source.unsplash.com/1000x700/?FRANCIA%20PRIVATE%20POOL",
    description: "A private pool and hotel where you can enjoy quality time with your love ones.",
    location: "Morera, Guinobatan, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "152",
    name: "UNCLE TOM'S BLUE SPRING RESORT",
    image: "https://source.unsplash.com/1000x700/?UNCLE%20TOM'S%20BLUE%20SPRING%20RESORT",
    description: "Located in the quiet baranggay of Quibongbongan, Guinobatan, Albay, with its Mountain Spring Flowing Water, Friendly Staff, Cheap Cottages and ZERO corkage fees. Our resort offers fun, relaxing getaway from the stress of the city life.",
    location: "Quibongbongan, Guinobatan, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "153",
    name: "Villa Acosta Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Villa%20Acosta%20Beach%20Resort",
    description: "Has a wide space for Beach goers and 2 big size swimming pool with slides where your family and friends can enjoy.",
    location: "San Isidro, Santo Domingo, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "154",
    name: "Anoling Radar Bike Park and Trail",
    image: "https://source.unsplash.com/1000x700/?Anoling%20Radar%20Bike%20Park%20and%20Trail",
    description: "The site is located within the countryside of the Mayon Volcano. Approximately 3 kms. from the Salugan-Anoling Junction. The nearest attraction is El Miro De Shie Integrated Farm. The site offers a thrilling bike trail while enjoying the scenic view of the foot and scenery of the majestic volcano.",
    location: "Anoling, Camalig, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "155",
    name: "MAYON SHOOTING AND HUNTING SPORTS CLUB",
    image: "https://source.unsplash.com/1000x700/?MAYON%20SHOOTING%20AND%20HUNTING%20SPORTS%20CLUB",
    description: "FIRING RANGE",
    location: "Ilawod, Guinobatan, Albay",
    category: "Other Sports and Recreational Activities",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "156",
    name: "KRIS FAITH OF NOAH RESORT",
    image: "https://source.unsplash.com/1000x700/?KRIS%20FAITH%20OF%20NOAH%20RESORT",
    description: "Very relaxing ambiance  Friendly staffs Jacuzzi at its best!",
    location: "San Francisco, Guinobatan, Albay",
    category: "Pools and Springs",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "157",
    name: "Pasalubong Center",
    image: "https://source.unsplash.com/1000x700/?Pasalubong%20Center",
    description: "A one-stop shop for products made in Tabaco such as cutlery products, handicrafts, souvenirs, gift items, etc. Located at Tabaco City Mall.",
    location: "Divino Rostro, Tabaco City, Albay",
    category: "Souvenirs and Delicacies",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "158",
    name: "MORATO PILI SWEETS",
    image: "https://source.unsplash.com/1000x700/?MORATO%20PILI%20SWEETS",
    description: "Home of Original Pure Pilinut Candies Since 1948",
    location: "Poblacion, Guinobatan, Albay",
    category: "Souvenirs and Delicacies",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "159",
    name: "MARCON FOOD ENTERPRISES",
    image: "https://source.unsplash.com/1000x700/?MARCON%20FOOD%20ENTERPRISES",
    description: "Magsino's Pili Nut Candies The best tasting pili products from Albay Well known for their Mazapan de Pili",
    location: "Lower Binogsacan, Guinobatan, Albay",
    category: "Souvenirs and Delicacies",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "160",
    name: "Embarcadero de Legazpi",
    image: "https://source.unsplash.com/1000x700/?Embarcadero%20de%20Legazpi",
    description: "A world-class waterfront lifestyle hub at the Legazpi City harbor, the first of its kind in Southern Luzon. Bicol's premier urban mall.",
    location: "Victory Village, Legazpi City, Albay",
    category: "Malls, Department Stores",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "161",
    name: "SEAN SUSAN FOOD PRODUCTS",
    image: "https://source.unsplash.com/1000x700/?SEAN%20SUSAN%20FOOD%20PRODUCTS",
    description: "Sean-Susan Food Products had been managing their business for more than ten (10) years making them stable in the business industry.",
    location: "Iraya, Guinobatan, Albay",
    category: "Souvenirs and Delicacies",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "162",
    name: "RAVAGO'S MEAT PRODUCTS",
    image: "https://source.unsplash.com/1000x700/?RAVAGO'S%20MEAT%20PRODUCTS",
    description: "Longganiza de Guinobatan",
    location: "Iraya, Guinobatan, Albay",
    category: "Souvenirs and Delicacies",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "163",
    name: "Nito-Talahib Festival",
    image: "https://source.unsplash.com/1000x700/?Nito-Talahib%20Festival",
    description: "The festival, celebrated every October 14-23, brings honor to the Nito-Talahib, also known as common grass or kans grass, wgich plays a vital part in the history of the place and in the lives of people in Manito.",
    location: "It-Ba, Manito, Albay",
    category: "Festivals (e.g. Official or de facto cultural heritage/community related)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "164",
    name: "Tabak Festival",
    image: "https://source.unsplash.com/1000x700/?Tabak%20Festival",
    description: "An annual celebration of the artistry of Tabaqueños through their crafts in producing the well-known \"Tabak\" and other cutlery products. Tabak Festival is celebrated every June 16-25.",
    location: "Quinale, Tabaco City, Albay",
    category: "Festivals (e.g. Official or de facto cultural heritage/community related)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "165",
    name: "Pasyon Tabaknon (Alalay Lakad)",
    image: "https://source.unsplash.com/1000x700/?Pasyon%20Tabaknon%20(Alalay%20Lakad)",
    description: "An annual tradition of the Tabaqueños that reflects our strong faith in God. This is a pilgrimage done every Maundy Thursday until Good Friday from Barangay Buang junction to Mayon Planetarium.",
    location: "Buang, Tabaco City, Albay",
    category: "Local Culture and Traditions (includes social practices and rituals)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "166",
    name: "Libon Paroy Festival",
    image: "https://source.unsplash.com/1000x700/?Libon%20Paroy%20Festival",
    description: "Paroy Festival celebrates Libon’s agricultural heritage as the \"Rice Granary of Albay\" as well as the town’s opulent past as one of the oldest settlements (Spanish Villas) in the country. Celebrated on July, it pays homage to Santiago el Mayor, the town's patron and its industrious farmers.",
    location: "Poblacion, Libon, Albay",
    category: "Festivals (e.g. Official or de facto cultural heritage/community related)",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "167",
    name: "Pasko Tabaqueño",
    image: "https://source.unsplash.com/1000x700/?Pasko%20Tabaqueño",
    description: "It is Tabaco City's vibrant and tradition-laden celebration of Christmas which promotes Tabaco as the \"New Christmas Destination\" in the Bicol Region.",
    location: "Quinale, Tabaco City, Albay",
    category: "Other Events",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "168",
    name: "CASA BASILISA INC",
    image: "https://source.unsplash.com/1000x700/?CASA%20BASILISA%20INC",
    description: "Casa Basilisa is a special interest resort located along national road at Barangay San Rafael,Guinobatan,Albay,Philippines. An ideal place to rest & rejuvenate.",
    location: "San Rafael, Guinobatan, Albay",
    category: "Convention",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "169",
    name: "CHARISMA SNACKHOUSE AND CATERING SERVICES",
    image: "https://source.unsplash.com/1000x700/?CHARISMA%20SNACKHOUSE%20AND%20CATERING%20SERVICES",
    description: "We offer different types of catering packages. We have function halls for different type of occasions. Our packages include event staff, sound system, tables and chairs, utensils and decorations such as table skirting and backdrop.",
    location: "San Rafael, Guinobatan, Albay",
    category: "Convention",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "170",
    name: "DREAMER'S KITCHEN AND FUNCTION HALL",
    image: "https://source.unsplash.com/1000x700/?DREAMER'S%20KITCHEN%20AND%20FUNCTION%20HALL",
    description: "Restaurants, Events, KTV Rooms, Buffet",
    location: "Iraya, Guinobatan, Albay",
    category: "Convention",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "171",
    name: "FEED HUNGRY MINDS LIBRARY, Inc.",
    image: "https://source.unsplash.com/1000x700/?FEED%20HUNGRY%20MINDS%20LIBRARY,%20Inc.",
    description: "A non profit organization, aims to develop the “love for reading” a reach out program, basically to provide tools for research, for students who has Dreams but less means. This public library collects old books and reading materials and old computers from friends and volunteers.",
    location: "Lower Binogsacan, Guinobatan, Albay",
    category: "Others",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "172",
    name: "Albay Farmers Bounty Village",
    image: "https://source.unsplash.com/1000x700/?Albay%20Farmers%20Bounty%20Village",
    description: "A DOT Accredited Farm Site owned and managed by the Provincial Government of Albay, approximately three (3) kms. from the Poblacion (Camalig Town Center) and 11 kms from Legazpi City, the nearest growth center.",
    location: "Barangay Cabangan, Camalig, Albay",
    category: "Education Tourism",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "173",
    name: "Reyes Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Reyes%20Beach%20Resort",
    description: "Reyes Beach Resort is a full service lodging facility and beach resort, intended primarily for families, individuals and vacationers. Established since 1970. Offers paid Wi-Fi. Free breakfast for two with overnight stay.",
    location: "Calayucay, Santo Domingo, Albay",
    category: "Others",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "174",
    name: "Coastal View Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Coastal%20View%20Beach%20Resort",
    description: "Coastal View Beach Resort consists of room services, organizing events and good for swimming outdoors along your friends and families with a scenic view of beach front and Mayon Volcano.",
    location: "Calayucay, Santo Domingo, Albay",
    category: "Others",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "175",
    name: "Aguas Farm",
    image: "https://source.unsplash.com/1000x700/?Aguas%20Farm",
    description: "Good food, animal interactions, music jammin' and a relaxing place where you can enjoy the scenic view of Mount Mayon.",
    location: "Fidel Surtida, Santo Domingo, Albay",
    category: "Others",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "176",
    name: "Camvias Farm Resort",
    image: "https://source.unsplash.com/1000x700/?Camvias%20Farm%20Resort",
    description: "Camvias Farm Resort brought its good ambiance that feels like its everyday summer. A nature-friendly environment that it also has a farm.",
    location: "Sta. Misericordia, Santo Domingo, Albay",
    category: "Others",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "177",
    name: "Manhattan Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Manhattan%20Beach%20Resort",
    description: "Enticingly overlooking the Albay Gulf with a black sand beach and the beautiful scenic view of the Mayon Volcano, Manhattan Beach Resort is the place for any kind of gatherings, whether it is a family reunion, personal retreats or business function.",
    location: "Calayucay, Santo Domingo, Albay",
    category: "Others",
    openingHours: "8:00 AM - 5:00 PM",
  },
  {
    id: "178",
    name: "Magnum Royale Beach Resort",
    image: "https://source.unsplash.com/1000x700/?Magnum%20Royale%20Beach%20Resort",
    description: "Magnum Royale Beach Resort embraces to you the kind of relaxation and a summer vibe through its beachfront view of Albay Gulf.",
    location: "Calayucay, Santo Domingo, Albay",
    category: "Others",
    openingHours: "8:00 AM - 5:00 PM",
  },
];

const DestinationsList = () => {
  return (
    <div className="w-full max-w-7xl mx-auto px-4 py-8">
      <h2 className="text-3xl font-bold text-gray-900 mb-6">
        Destinations in Albay
      </h2>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {destinations.map((spot) => (
          <DestinationsCard key={spot.id} {...spot} />
        ))}
      </div>
    </div>
  );
};

export default DestinationsList;
